# Applies the following labels to pull requests whenver they are created or modified:
#  - pr: documentation
#  - pr: programming
#  - pr: github
# see .github/labeler.yml and .github/changed-lines-count-labeler.yml

name: "Pull Request Labeler"
on:
- pull_request_target

# Ensure only one task can execute for a given PR at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  queue: max

jobs:
  # Apply labels to pull requests based on which files were edited
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Set basic labels
      uses: actions/labeler@v6
      with:
        sync-labels: true